[versions]
agp = "8.13.0"
kotlin = "2.2.20"
spotless = "8.0.0"
androidxCoreKtx = "1.17.0"
lifecycle = "2.9.4"
coroutinesAndroid = "1.10.2"
kotlinxSerialization = "1.9.0"
webkit = "1.14.0"
datastorePreferences = "1.1.7"
securityCrypto = "1.1.0"
okhttp = "5.2.1"
junit = "4.13.2"
androidxTestExt = "1.3.0"
androidxTestRunner = "1.7.0"
mockk = "1.14.6"
androidxTestCore = "1.7.0"
robolectric = "4.16"
coroutinesTest = "1.10.2"

[libraries]
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidxLifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesAndroid" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
androidxWebkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
androidxDatastorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidxSecurityCrypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
junit = { module = "junit:junit", version.ref = "junit" }
androidxTestExt = { module = "androidx.test.ext:junit", version.ref = "androidxTestExt" }
androidxTestRunner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
androidxTestCore = { module = "androidx.test:core-ktx", version.ref = "androidxTestCore" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
shadowsFramework = { module = "org.robolectric:shadows-framework", version.ref = "robolectric" }
kotlinxCoroutinesTest = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
