[versions]
agp = "8.13.0"
kotlin = "2.2.20"
spotless = "8.0.0"
androidxCoreKtx = "1.17.0"
androidxAppcompat = "1.7.1"
material = "1.13.0"
androidxActivity = "1.11.0"
constraintLayout = "2.2.1"
composeBom = "2025.10.00"
lifecycle = "2.9.4"
coroutinesAndroid = "1.10.2"
kotlinxSerialization = "1.9.0"
webkit = "1.14.0"
datastorePreferences = "1.1.7"
securityCrypto = "1.1.0"

[libraries]
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidxAppcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
googleMaterial = { module = "com.google.android.material:material", version.ref = "material" }
androidxActivityKtx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidxConstraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidxComposeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidxComposeUi = { module = "androidx.compose.ui:ui" }
androidxComposeMaterial3 = { module = "androidx.compose.material3:material3" }
androidxComposeMaterialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidxComposeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidxComposeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
androidxLifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidxLifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesAndroid" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
androidxWebkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
androidxDatastorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidxSecurityCrypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
