[versions]
agp = "8.13.2"
kotlin = "2.2.20"
ksp = "2.2.20-2.0.4"
leakcanaryAndroid = "2.14"
spotless = "8.1.0"
androidxCoreKtx = "1.17.0"
androidxAppcompat = "1.7.1"
material = "1.13.0"
androidxActivity = "1.12.2"
constraintLayout = "2.2.1"
composeBom = "2025.12.01"
lifecycle = "2.10.0"
coroutinesAndroid = "1.10.2"
kotlinxSerialization = "1.9.0"
tinkAndroid = "1.20.0"
walletkitAndroid = "0.0.1"
webkit = "1.15.0"
datastorePreferences = "1.2.0"
securityCrypto = "1.1.0"
coil = "3.3.0"
hilt = "2.57.2"
# Testing
junit = "4.13.2"
androidxTestCore = "1.7.0"
androidxTestRunner = "1.7.0"
androidxTestRules = "1.7.0"
androidxTestEspresso = "3.7.0"
androidxTestUiAutomator = "2.3.0"
allureKotlin = "2.4.0"
okhttp = "5.3.2"

[libraries]
androidxCoreKtx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidxAppcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidxAppcompat" }
googleMaterial = { module = "com.google.android.material:material", version.ref = "material" }
androidxActivityKtx = { module = "androidx.activity:activity-ktx", version.ref = "androidxActivity" }
androidxConstraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
androidxActivityCompose = { module = "androidx.activity:activity-compose", version.ref = "androidxActivity" }
androidxComposeBom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidxComposeUi = { module = "androidx.compose.ui:ui" }
androidxComposeMaterial3 = { module = "androidx.compose.material3:material3" }
androidxComposeMaterialIconsExtended = { module = "androidx.compose.material:material-icons-extended" }
androidxComposeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidxComposeUiTooling = { module = "androidx.compose.ui:ui-tooling" }
androidxLifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidxLifecycleViewmodelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesAndroid" }
kotlinxSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
androidxWebkit = { module = "androidx.webkit:webkit", version.ref = "webkit" }
androidxDatastorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
androidxSecurityCrypto = { module = "androidx.security:security-crypto", version.ref = "securityCrypto" }
leakcanaryAndroid = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanaryAndroid" }
coilCompose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil" }
coilNetwork = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coil" }
hiltAndroid = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hiltCompiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
# Testing
junit = { module = "junit:junit", version.ref = "junit" }
androidxTestCore = { module = "androidx.test:core", version.ref = "androidxTestCore" }
androidxTestCoreKtx = { module = "androidx.test:core-ktx", version.ref = "androidxTestCore" }
androidxTestRunner = { module = "androidx.test:runner", version.ref = "androidxTestRunner" }
androidxTestRules = { module = "androidx.test:rules", version.ref = "androidxTestRules" }
androidxTestEspressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspresso" }
androidxTestEspressoWeb = { module = "androidx.test.espresso:espresso-web", version.ref = "androidxTestEspresso" }
androidxTestEspressoIntents = { module = "androidx.test.espresso:espresso-intents", version.ref = "androidxTestEspresso" }
androidxTestUiAutomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidxTestUiAutomator" }
androidxComposeUiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidxComposeUiTestManifest = { module = "androidx.compose.ui:ui-test-manifest" }
allureKotlinAndroid = { module = "io.qameta.allure:allure-kotlin-android", version.ref = "allureKotlin" }
allureKotlinModel = { module = "io.qameta.allure:allure-kotlin-model", version.ref = "allureKotlin" }
allureKotlinCommons = { module = "io.qameta.allure:allure-kotlin-commons", version.ref = "allureKotlin" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
hiltAndroidTesting = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }
tinkAndroid = { module = "com.google.crypto.tink:tink-android", version.ref = "tinkAndroid" }
walletkitAndroid = { module = "org.ton:walletkit-android", version.ref = "walletkitAndroid" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinCompose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hiltAndroid = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
